# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(661, 585)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.graphicsView_seq1 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_seq1.setObjectName("graphicsView_seq1")
        self.gridLayout_4.addWidget(self.graphicsView_seq1, 0, 1, 1, 1)
        self.graphicsView_phantom = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_phantom.setObjectName("graphicsView_phantom")
        self.gridLayout_4.addWidget(self.graphicsView_phantom, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 1, 0, 1, 6)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 3, 1, 1)
        self.GV_prep = PlotWidget(self.tab)
        self.GV_prep.setObjectName("GV_prep")
        self.gridLayout_2.addWidget(self.GV_prep, 3, 0, 1, 3)
        self.GV_aqua = PlotWidget(self.tab)
        self.GV_aqua.setObjectName("GV_aqua")
        self.gridLayout_2.addWidget(self.GV_aqua, 3, 3, 1, 3)
        self.size_2 = QtWidgets.QComboBox(self.tab)
        self.size_2.setStyleSheet("")
        self.size_2.setEditable(True)
        self.size_2.setIconSize(QtCore.QSize(40, 40))
        self.size_2.setDuplicatesEnabled(False)
        self.size_2.setObjectName("size_2")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.gridLayout_2.addWidget(self.size_2, 4, 0, 1, 1)
        self.browse = QtWidgets.QPushButton(self.tab)
        self.browse.setStyleSheet("")
        self.browse.setObjectName("browse")
        self.gridLayout_2.addWidget(self.browse, 4, 1, 1, 1)
        self.property_2 = QtWidgets.QComboBox(self.tab)
        self.property_2.setStyleSheet("")
        self.property_2.setEditable(True)
        self.property_2.setIconSize(QtCore.QSize(40, 40))
        self.property_2.setObjectName("property_2")
        self.property_2.addItem("")
        self.property_2.addItem("")
        self.property_2.addItem("")
        self.property_2.addItem("")
        self.gridLayout_2.addWidget(self.property_2, 4, 2, 1, 1)
        self.Ernst_Angle = QtWidgets.QPushButton(self.tab)
        self.Ernst_Angle.setStyleSheet("")
        self.Ernst_Angle.setObjectName("Ernst_Angle")
        self.gridLayout_2.addWidget(self.Ernst_Angle, 4, 3, 1, 1)
        self.Acquisition_Box = QtWidgets.QComboBox(self.tab)
        self.Acquisition_Box.setStyleSheet("")
        self.Acquisition_Box.setObjectName("Acquisition_Box")
        self.Acquisition_Box.addItem("")
        self.Acquisition_Box.addItem("")
        self.Acquisition_Box.addItem("")
        self.Acquisition_Box.addItem("")
        self.gridLayout_2.addWidget(self.Acquisition_Box, 4, 4, 1, 1)
        self.Preparetion_Box = QtWidgets.QComboBox(self.tab)
        self.Preparetion_Box.setStyleSheet("")
        self.Preparetion_Box.setObjectName("Preparetion_Box")
        self.Preparetion_Box.addItem("")
        self.Preparetion_Box.addItem("")
        self.Preparetion_Box.addItem("")
        self.Preparetion_Box.addItem("")
        self.gridLayout_2.addWidget(self.Preparetion_Box, 4, 5, 1, 1)
        self.TR_Edit = QtWidgets.QLineEdit(self.tab)
        self.TR_Edit.setText("")
        self.TR_Edit.setObjectName("TR_Edit")
        self.gridLayout_2.addWidget(self.TR_Edit, 5, 0, 1, 2)
        self.TE_Edit = QtWidgets.QLineEdit(self.tab)
        self.TE_Edit.setText("")
        self.TE_Edit.setObjectName("TE_Edit")
        self.gridLayout_2.addWidget(self.TE_Edit, 5, 2, 1, 2)
        self.Zooming_Box = QtWidgets.QComboBox(self.tab)
        self.Zooming_Box.setStyleSheet("")
        self.Zooming_Box.setObjectName("Zooming_Box")
        self.Zooming_Box.addItem("")
        self.Zooming_Box.addItem("")
        self.Zooming_Box.addItem("")
        self.gridLayout_2.addWidget(self.Zooming_Box, 5, 4, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 5, 5, 1, 1)
        self.Start_seq1 = QtWidgets.QPushButton(self.tab)
        self.Start_seq1.setStyleSheet("")
        self.Start_seq1.setObjectName("Start_seq1")
        self.gridLayout_2.addWidget(self.Start_seq1, 0, 1, 1, 4)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.image = QtWidgets.QLabel(self.tab_3)
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.gridLayout_3.addWidget(self.image, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 1, 1, 1)
        self.Brightness_slider = QtWidgets.QSlider(self.tab_3)
        self.Brightness_slider.setMinimum(-10)
        self.Brightness_slider.setMaximum(10)
        self.Brightness_slider.setOrientation(QtCore.Qt.Vertical)
        self.Brightness_slider.setObjectName("Brightness_slider")
        self.gridLayout_3.addWidget(self.Brightness_slider, 0, 2, 1, 1)
        self.graph_t1 = PlotWidget(self.tab_3)
        self.graph_t1.setObjectName("graph_t1")
        self.gridLayout_3.addWidget(self.graph_t1, 1, 0, 1, 1)
        self.graph_t2 = PlotWidget(self.tab_3)
        self.graph_t2.setObjectName("graph_t2")
        self.gridLayout_3.addWidget(self.graph_t2, 1, 1, 1, 1)
        self.Contrast_slider = QtWidgets.QSlider(self.tab_3)
        self.Contrast_slider.setMinimum(-10)
        self.Contrast_slider.setMaximum(10)
        self.Contrast_slider.setOrientation(QtCore.Qt.Vertical)
        self.Contrast_slider.setObjectName("Contrast_slider")
        self.gridLayout_3.addWidget(self.Contrast_slider, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Prepration"))
        self.label_2.setText(_translate("MainWindow", "Acquazition"))
        self.size_2.setCurrentText(_translate("MainWindow", "Size"))
        self.size_2.setItemText(0, _translate("MainWindow", "Size"))
        self.size_2.setItemText(1, _translate("MainWindow", "20"))
        self.size_2.setItemText(2, _translate("MainWindow", "64"))
        self.size_2.setItemText(3, _translate("MainWindow", "128"))
        self.size_2.setItemText(4, _translate("MainWindow", "256"))
        self.size_2.setItemText(5, _translate("MainWindow", "512"))
        self.browse.setText(_translate("MainWindow", "Broswe"))
        self.property_2.setCurrentText(_translate("MainWindow", "Property"))
        self.property_2.setItemText(0, _translate("MainWindow", "Property"))
        self.property_2.setItemText(1, _translate("MainWindow", "T1"))
        self.property_2.setItemText(2, _translate("MainWindow", "T2"))
        self.property_2.setItemText(3, _translate("MainWindow", "Phantom"))
        self.Ernst_Angle.setText(_translate("MainWindow", "Ernst Angle"))
        self.Acquisition_Box.setItemText(0, _translate("MainWindow", "Acquisition"))
        self.Acquisition_Box.setItemText(1, _translate("MainWindow", "GRE"))
        self.Acquisition_Box.setItemText(2, _translate("MainWindow", "SSFP"))
        self.Acquisition_Box.setItemText(3, _translate("MainWindow", "SE"))
        self.Preparetion_Box.setItemText(0, _translate("MainWindow", "Preparetion"))
        self.Preparetion_Box.setItemText(1, _translate("MainWindow", "T1 Prep (IR)"))
        self.Preparetion_Box.setItemText(2, _translate("MainWindow", "T2  Prep"))
        self.Preparetion_Box.setItemText(3, _translate("MainWindow", "Tagging Prep"))
        self.TR_Edit.setPlaceholderText(_translate("MainWindow", "Enter TR"))
        self.TE_Edit.setPlaceholderText(_translate("MainWindow", "Enter TE"))
        self.Zooming_Box.setCurrentText(_translate("MainWindow", "Zooming"))
        self.Zooming_Box.setItemText(0, _translate("MainWindow", "Zooming"))
        self.Zooming_Box.setItemText(1, _translate("MainWindow", "Without Link"))
        self.Zooming_Box.setItemText(2, _translate("MainWindow", "With Link"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Artifacts"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Alaising"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Bluring"))
        self.Start_seq1.setText(_translate("MainWindow", "Start Sequence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "View Port 1"))
        self.image.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Phantom"))


from pyqtgraph import PlotWidget
