# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Final.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(631, 626)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 586, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.Preparetion_Box = QtWidgets.QComboBox(self.tab)
        self.Preparetion_Box.setStyleSheet("")
        self.Preparetion_Box.setObjectName("Preparetion_Box")
        self.Preparetion_Box.addItem("")
        self.Preparetion_Box.addItem("")
        self.Preparetion_Box.addItem("")
        self.Preparetion_Box.addItem("")
        self.gridLayout_2.addWidget(self.Preparetion_Box, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 3)
        self.GV_prep = PlotWidget(self.tab)
        self.GV_prep.setObjectName("GV_prep")
        self.gridLayout_2.addWidget(self.GV_prep, 2, 3, 1, 2)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 3, 1, 2)
        self.GV_aqua = PlotWidget(self.tab)
        self.GV_aqua.setObjectName("GV_aqua")
        self.gridLayout_2.addWidget(self.GV_aqua, 2, 0, 1, 3)
        self.Ernst_Angle = QtWidgets.QPushButton(self.tab)
        self.Ernst_Angle.setStyleSheet("")
        self.Ernst_Angle.setObjectName("Ernst_Angle")
        self.gridLayout_2.addWidget(self.Ernst_Angle, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setStyleSheet("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 3, 3, 1, 1)
        self.Zooming_Box = QtWidgets.QComboBox(self.tab)
        self.Zooming_Box.setStyleSheet("")
        self.Zooming_Box.setObjectName("Zooming_Box")
        self.Zooming_Box.addItem("")
        self.Zooming_Box.addItem("")
        self.Zooming_Box.addItem("")
        self.gridLayout_2.addWidget(self.Zooming_Box, 3, 4, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Start_seq1 = QtWidgets.QPushButton(self.tab)
        self.Start_seq1.setStyleSheet("")
        self.Start_seq1.setObjectName("Start_seq1")
        self.verticalLayout_2.addWidget(self.Start_seq1)
        self.graphicsView_seq1 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_seq1.setObjectName("graphicsView_seq1")
        self.verticalLayout_2.addWidget(self.graphicsView_seq1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 3)
        self.Acquisition_Box = QtWidgets.QComboBox(self.tab)
        self.Acquisition_Box.setStyleSheet("")
        self.Acquisition_Box.setObjectName("Acquisition_Box")
        self.Acquisition_Box.addItem("")
        self.Acquisition_Box.addItem("")
        self.Acquisition_Box.addItem("")
        self.Acquisition_Box.addItem("")
        self.gridLayout_2.addWidget(self.Acquisition_Box, 3, 2, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_phantom = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView_phantom.setObjectName("graphicsView_phantom")
        self.verticalLayout.addWidget(self.graphicsView_phantom)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.image = QtWidgets.QLabel(self.tab_3)
        self.image.setMinimumSize(QtCore.QSize(200, 200))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setText("")
        self.image.setScaledContents(True)
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 2, 1, 1)
        self.Brightness_slider = QtWidgets.QSlider(self.tab_3)
        self.Brightness_slider.setMinimum(-10)
        self.Brightness_slider.setMaximum(10)
        self.Brightness_slider.setOrientation(QtCore.Qt.Vertical)
        self.Brightness_slider.setObjectName("Brightness_slider")
        self.gridLayout.addWidget(self.Brightness_slider, 0, 3, 1, 1)
        self.Decay_label = QtWidgets.QLabel(self.tab_3)
        self.Decay_label.setScaledContents(True)
        self.Decay_label.setObjectName("Decay_label")
        self.gridLayout.addWidget(self.Decay_label, 1, 0, 1, 1)
        self.Recovery_label = QtWidgets.QLabel(self.tab_3)
        self.Recovery_label.setScaledContents(True)
        self.Recovery_label.setObjectName("Recovery_label")
        self.gridLayout.addWidget(self.Recovery_label, 1, 2, 1, 1)
        self.graph_t2 = PlotWidget(self.tab_3)
        self.graph_t2.setObjectName("graph_t2")
        self.gridLayout.addWidget(self.graph_t2, 2, 0, 1, 2)
        self.graph_t1 = PlotWidget(self.tab_3)
        self.graph_t1.setObjectName("graph_t1")
        self.gridLayout.addWidget(self.graph_t1, 2, 2, 1, 1)
        self.Contrast_slider = QtWidgets.QSlider(self.tab_3)
        self.Contrast_slider.setMinimum(-10)
        self.Contrast_slider.setMaximum(10)
        self.Contrast_slider.setOrientation(QtCore.Qt.Vertical)
        self.Contrast_slider.setObjectName("Contrast_slider")
        self.gridLayout.addWidget(self.Contrast_slider, 2, 3, 1, 1)
        self.splitter = QtWidgets.QSplitter(self.tab_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.size_2 = QtWidgets.QComboBox(self.splitter_2)
        self.size_2.setStyleSheet("")
        self.size_2.setEditable(True)
        self.size_2.setIconSize(QtCore.QSize(40, 40))
        self.size_2.setDuplicatesEnabled(False)
        self.size_2.setObjectName("size_2")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.size_2.addItem("")
        self.browse = QtWidgets.QPushButton(self.splitter_2)
        self.browse.setStyleSheet("")
        self.browse.setObjectName("browse")
        self.property_2 = QtWidgets.QComboBox(self.splitter_2)
        self.property_2.setStyleSheet("")
        self.property_2.setEditable(True)
        self.property_2.setIconSize(QtCore.QSize(40, 40))
        self.property_2.setObjectName("property_2")
        self.property_2.addItem("")
        self.property_2.addItem("")
        self.property_2.addItem("")
        self.property_2.addItem("")
        self.TE_Edit = QtWidgets.QLineEdit(self.splitter_2)
        self.TE_Edit.setText("")
        self.TE_Edit.setObjectName("TE_Edit")
        self.TR_Edit = QtWidgets.QLineEdit(self.splitter_2)
        self.TR_Edit.setText("")
        self.TR_Edit.setObjectName("TR_Edit")
        self.gridLayout.addWidget(self.splitter, 3, 0, 2, 1)
        self.FA_Edit_4 = QtWidgets.QLineEdit(self.tab_3)
        self.FA_Edit_4.setText("")
        self.FA_Edit_4.setObjectName("FA_Edit_4")
        self.gridLayout.addWidget(self.FA_Edit_4, 3, 1, 1, 1)
        self.ST_Edit_5 = QtWidgets.QLineEdit(self.tab_3)
        self.ST_Edit_5.setText("")
        self.ST_Edit_5.setObjectName("ST_Edit_5")
        self.gridLayout.addWidget(self.ST_Edit_5, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Preparetion_Box.setItemText(0, _translate("MainWindow", "Preparetion"))
        self.Preparetion_Box.setItemText(1, _translate("MainWindow", "T1 Prep (IR)"))
        self.Preparetion_Box.setItemText(2, _translate("MainWindow", "T2  Prep"))
        self.Preparetion_Box.setItemText(3, _translate("MainWindow", "Tagging Prep"))
        self.label_2.setText(_translate("MainWindow", "Acquasition"))
        self.label.setText(_translate("MainWindow", "Preparation"))
        self.Ernst_Angle.setText(_translate("MainWindow", "Ernst Angle"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Artifacts"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Alaising"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Bluring"))
        self.Zooming_Box.setCurrentText(_translate("MainWindow", "Zooming"))
        self.Zooming_Box.setItemText(0, _translate("MainWindow", "Zooming"))
        self.Zooming_Box.setItemText(1, _translate("MainWindow", "Without Link"))
        self.Zooming_Box.setItemText(2, _translate("MainWindow", "With Link"))
        self.Start_seq1.setText(_translate("MainWindow", "Start"))
        self.Acquisition_Box.setItemText(0, _translate("MainWindow", "Acquisition"))
        self.Acquisition_Box.setItemText(1, _translate("MainWindow", "GRE"))
        self.Acquisition_Box.setItemText(2, _translate("MainWindow", "SSFP"))
        self.Acquisition_Box.setItemText(3, _translate("MainWindow", "SE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "View Port 1"))
        self.Decay_label.setText(_translate("MainWindow", "Decay"))
        self.Recovery_label.setText(_translate("MainWindow", " Recovey"))
        self.size_2.setCurrentText(_translate("MainWindow", "Size"))
        self.size_2.setItemText(0, _translate("MainWindow", "Size"))
        self.size_2.setItemText(1, _translate("MainWindow", "20"))
        self.size_2.setItemText(2, _translate("MainWindow", "64"))
        self.size_2.setItemText(3, _translate("MainWindow", "128"))
        self.size_2.setItemText(4, _translate("MainWindow", "256"))
        self.size_2.setItemText(5, _translate("MainWindow", "512"))
        self.browse.setText(_translate("MainWindow", "Broswe"))
        self.property_2.setCurrentText(_translate("MainWindow", "Property"))
        self.property_2.setItemText(0, _translate("MainWindow", "Property"))
        self.property_2.setItemText(1, _translate("MainWindow", "T1"))
        self.property_2.setItemText(2, _translate("MainWindow", "T2"))
        self.property_2.setItemText(3, _translate("MainWindow", "Phantom"))
        self.TE_Edit.setPlaceholderText(_translate("MainWindow", "Enter TE"))
        self.TR_Edit.setPlaceholderText(_translate("MainWindow", "Enter TR"))
        self.FA_Edit_4.setPlaceholderText(_translate("MainWindow", "Enter FA"))
        self.ST_Edit_5.setPlaceholderText(_translate("MainWindow", "Enter ST"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Phantom"))


from pyqtgraph import PlotWidget
