# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nt2.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(578, 533)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.contrast = QtWidgets.QSlider(self.tab)
        self.contrast.setGeometry(QtCore.QRect(523, 220, 22, 191))
        self.contrast.setMinimum(1)
        self.contrast.setMaximum(10)
        self.contrast.setOrientation(QtCore.Qt.Vertical)
        self.contrast.setObjectName("contrast")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(9, 431, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.brightness = QtWidgets.QSlider(self.tab)
        self.brightness.setGeometry(QtCore.QRect(523, 9, 22, 181))
        self.brightness.setMinimum(1)
        self.brightness.setMaximum(10)
        self.brightness.setOrientation(QtCore.Qt.Vertical)
        self.brightness.setObjectName("brightness")
        self.spinBox_TR = QtWidgets.QSpinBox(self.tab)
        self.spinBox_TR.setGeometry(QtCore.QRect(55, 460, 55, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_TR.sizePolicy().hasHeightForWidth())
        self.spinBox_TR.setSizePolicy(sizePolicy)
        self.spinBox_TR.setMaximum(10000)
        self.spinBox_TR.setSingleStep(100)
        self.spinBox_TR.setProperty("value", 0)
        self.spinBox_TR.setObjectName("spinBox_TR")
        self.spinBox_stcy = QtWidgets.QSpinBox(self.tab)
        self.spinBox_stcy.setGeometry(QtCore.QRect(483, 460, 37, 20))
        self.spinBox_stcy.setSingleStep(10)
        self.spinBox_stcy.setProperty("value", 0)
        self.spinBox_stcy.setObjectName("spinBox_stcy")
        self.comboBox_prep = QtWidgets.QComboBox(self.tab)
        self.comboBox_prep.setGeometry(QtCore.QRect(255, 432, 82, 20))
        self.comboBox_prep.setObjectName("comboBox_prep")
        self.comboBox_prep.addItem("")
        self.comboBox_prep.addItem("")
        self.comboBox_prep.addItem("")
        self.comboBox_prep.addItem("")
        self.spinBox_TE = QtWidgets.QSpinBox(self.tab)
        self.spinBox_TE.setGeometry(QtCore.QRect(160, 460, 55, 20))
        self.spinBox_TE.setMaximum(10000)
        self.spinBox_TE.setSingleStep(10)
        self.spinBox_TE.setProperty("value", 0)
        self.spinBox_TE.setObjectName("spinBox_TE")
        self.graphicsView_t1 = PlotWidget(self.tab)
        self.graphicsView_t1.setGeometry(QtCore.QRect(255, 9, 256, 201))
        self.graphicsView_t1.setObjectName("graphicsView_t1")
        self.graphicsView_t2 = PlotWidget(self.tab)
        self.graphicsView_t2.setGeometry(QtCore.QRect(255, 220, 256, 192))
        self.graphicsView_t2.setObjectName("graphicsView_t2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(343, 431, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.comboBox_sp = QtWidgets.QComboBox(self.tab)
        self.comboBox_sp.setGeometry(QtCore.QRect(95, 432, 65, 20))
        self.comboBox_sp.setObjectName("comboBox_sp")
        self.comboBox_sp.addItem("")
        self.comboBox_sp.addItem("")
        self.comboBox_sp.addItem("")
        self.comboBox_sp.addItem("")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(9, 460, 40, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(299, 460, 70, 16))
        self.label_3.setObjectName("label_3")
        self.spinBox_FA = QtWidgets.QSpinBox(self.tab)
        self.spinBox_FA.setGeometry(QtCore.QRect(382, 460, 43, 20))
        self.spinBox_FA.setMaximum(180)
        self.spinBox_FA.setSingleStep(90)
        self.spinBox_FA.setProperty("value", 0)
        self.spinBox_FA.setObjectName("spinBox_FA")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(431, 460, 46, 16))
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(134, 460, 21, 16))
        self.label_2.setObjectName("label_2")
        self.comboBox_aqu = QtWidgets.QComboBox(self.tab)
        self.comboBox_aqu.setGeometry(QtCore.QRect(174, 432, 75, 20))
        self.comboBox_aqu.setObjectName("comboBox_aqu")
        self.comboBox_aqu.addItem("")
        self.comboBox_aqu.addItem("")
        self.comboBox_aqu.addItem("")
        self.comboBox_aqu.addItem("")
        self.phantom1 = QtWidgets.QLabel(self.tab)
        self.phantom1.setGeometry(QtCore.QRect(9, 9, 241, 201))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phantom1.sizePolicy().hasHeightForWidth())
        self.phantom1.setSizePolicy(sizePolicy)
        self.phantom1.setScaledContents(True)
        self.phantom1.setAlignment(QtCore.Qt.AlignCenter)
        self.phantom1.setObjectName("phantom1")
        self.phantom3 = QtWidgets.QLabel(self.tab)
        self.phantom3.setGeometry(QtCore.QRect(9, 220, 241, 191))
        self.phantom3.setScaledContents(True)
        self.phantom3.setAlignment(QtCore.Qt.AlignCenter)
        self.phantom3.setObjectName("phantom3")
        self.cbZoom = QtWidgets.QComboBox(self.tab)
        self.cbZoom.setGeometry(QtCore.QRect(430, 432, 61, 20))
        self.cbZoom.setObjectName("cbZoom")
        self.cbZoom.addItem("")
        self.cbZoom.addItem("")
        self.cbZoom.addItem("")
        self.spinBox = QtWidgets.QSpinBox(self.tab)
        self.spinBox.setGeometry(QtCore.QRect(290, 460, 42, 22))
        self.spinBox.setMaximum(1000)
        self.spinBox.setSingleStep(10)
        self.spinBox.setObjectName("spinBox")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(230, 460, 51, 21))
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.phantom6 = QtWidgets.QLabel(self.tab_2)
        self.phantom6.setGeometry(QtCore.QRect(290, 20, 251, 211))
        self.phantom6.setText("")
        self.phantom6.setScaledContents(True)
        self.phantom6.setAlignment(QtCore.Qt.AlignCenter)
        self.phantom6.setObjectName("phantom6")
        self.graphicsView = PlotWidget(self.tab_2)
        self.graphicsView.setGeometry(QtCore.QRect(15, 260, 521, 221))
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 10, 211, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.ernst_btttn = QtWidgets.QPushButton(self.tab_3)
        self.ernst_btttn.setGeometry(QtCore.QRect(220, 380, 75, 23))
        self.ernst_btttn.setObjectName("ernst_btttn")
        self.ernst_graph = PlotWidget(self.tab_3)
        self.ernst_graph.setGeometry(QtCore.QRect(80, 60, 371, 281))
        self.ernst_graph.setObjectName("ernst_graph")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Browse"))
        self.comboBox_prep.setItemText(0, _translate("Form", "Preparation"))
        self.comboBox_prep.setItemText(1, _translate("Form", "IR"))
        self.comboBox_prep.setItemText(2, _translate("Form", "T2_Prep"))
        self.comboBox_prep.setItemText(3, _translate("Form", "Tagging"))
        self.pushButton_2.setText(_translate("Form", "Kspace"))
        self.comboBox_sp.setItemText(0, _translate("Form", "O.Array"))
        self.comboBox_sp.setItemText(1, _translate("Form", "T1"))
        self.comboBox_sp.setItemText(2, _translate("Form", "T2"))
        self.comboBox_sp.setItemText(3, _translate("Form", "PD"))
        self.label.setText(_translate("Form", "         TR"))
        self.label_3.setText(_translate("Form", "                   FA"))
        self.label_4.setText(_translate("Form", "     ST_CY"))
        self.label_2.setText(_translate("Form", "  TE"))
        self.comboBox_aqu.setItemText(0, _translate("Form", "Acquistion"))
        self.comboBox_aqu.setItemText(1, _translate("Form", "GRE"))
        self.comboBox_aqu.setItemText(2, _translate("Form", "SSFP"))
        self.comboBox_aqu.setItemText(3, _translate("Form", "SE"))
        self.phantom1.setText(_translate("Form", "phantom1"))
        self.phantom3.setText(_translate("Form", "phantom2"))
        self.cbZoom.setItemText(0, _translate("Form", "zomming"))
        self.cbZoom.setItemText(1, _translate("Form", "separated"))
        self.cbZoom.setItemText(2, _translate("Form", "linked"))
        self.label_5.setText(_translate("Form", "           Ti"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.ernst_btttn.setText(_translate("Form", "ernst "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Page"))


from pyqtgraph import PlotWidget
